name: Build, Push and Update Frontend

on:
  push:
    branches:
      - main  # или другой основной ветвь

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shop_frontend:latest .

      - name: Push Docker image
        run: |
          docker push yourusername/shop_frontend:latest

      - name: SSH to VPS and pull latest Docker image
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/shop_frontend:latest
            cd /root/deploy-shop-docker-compose
            docker-compose up -d frontend
